#!/usr/bin/env bash
# configure nginx to listen on port 8080 ( edit default file) 
# configure nginx to run as nginx user ( rm www-data to user nginx) 
chmod 777 /etc/nginx/nginx.conf
sed -i "s/listen 80 default_server;/listen 8080 default_server;/" /etc/nginx/sites-enabled/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache
su nginx -c "service nginx restart" 
