#!/usr/bin/env bash
# configure nginx to listen on port 8080 ( edit default file) 
# configure nginx to run as nginx user ( rm www-data to user nginx) 
sed -1 "s/80/8080/g" /etc/nginx/sites-available/default
sed -1 "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache
su nginx -c "service nginx restart" 
