#!/usr/bin/env bash
# installing and running haproxy
sudo apt update
sudo apt install haproxy -y
load_balance_config=\
"backend my_servers
        balance roundrobin
	server 4846-web-01 107.21.62.186
	server 4846-web-o2 100.26.107.42
frontend haproxy_inbound
        bind *:80
        default_backend my_servers
        mode http
"
# enable haproxy to be managed by init script
sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo $load_balance_config >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
