#!/usr/bin/env bash
# install nginx web server on web-01 server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html 
sudo service nginx restart
