#!/usr/bin/env bash
# install nginx web server on web-01 server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo allow 'Nginx HTTP' 
sudo chmod 777 /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html 
sudo service nginx restart
